resource_group_name       = dev-resources
resource_group_location   = westeurope
environment               = "dev"
location                  = "westeurope"
description               = "Deploy a PostgreSQL Server"
owner                     = "Olena Gorodetska"
postgresql-admin-login    = "psqladmin"
postgresql-admin-password = "Th1sIsAP@ssw0rd"
postgresql-version        = "12"
postgresql-sku-name       = "B_Gen4_1"
postgresql-storage        = "5120"
